export const CATEGORIES = {
    ALL: 'All',
    DEVELOPER: 'Developer',
    DESIGN: 'Design',
    CONTENT: 'Content',
    SECURITY: 'Security',
    PRODUCTIVITY: 'Productivity',
    UTILITY: 'Utility',
    CONVERTER: 'Converter',
    AI: 'AI',
    DATA: 'Data',
    NETWORK: 'Network',
    SEO: 'SEO',
    MATH: 'Math',
};

export const toolsList = [
    // AI TOOLS (Featured First)
    {
        id: 'ai-text-summarizer',
        name: 'AI Text Summarizer',
        description: 'Summarize long text using AI',
        category: CATEGORIES.AI,
        path: '/tools/ai-text-summarizer',
        icon: '🤖',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },
    {
        id: 'ai-code-explainer',
        name: 'AI Code Explainer',
        description: 'Get explanations for code snippets',
        category: CATEGORIES.AI,
        path: '/tools/ai-code-explainer',
        icon: '💡',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },
    {
        id: 'ai-regex-generator',
        name: 'AI Regex Generator',
        description: 'Generate regex patterns from descriptions',
        category: CATEGORIES.AI,
        path: '/tools/ai-regex-generator',
        icon: '🔍',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },
    {
        id: 'ai-json-generator',
        name: 'AI JSON Generator',
        description: 'Generate JSON structures from descriptions',
        category: CATEGORIES.AI,
        path: '/tools/ai-json-generator',
        icon: '📋',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },
    {
        id: 'ai-sql-generator',
        name: 'AI SQL Generator',
        description: 'Generate SQL queries from descriptions',
        category: CATEGORIES.AI,
        path: '/tools/ai-sql-generator',
        icon: '🗃️',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },
    {
        id: 'ai-writing-assistant',
        name: 'AI Writing Assistant',
        description: 'Improve your technical writing',
        category: CATEGORIES.AI,
        path: '/tools/ai-writing-assistant',
        icon: '✍️',
        popular: true,
        requiresApiKey: true,
        aiProvider: 'any',
    },

    // DEVELOPER TOOLS
    {
        id: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Format, validate & beautify JSON instantly',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/json-formatter',
        icon: '{}',
        popular: true,
    },
    {
        id: 'base64-encoder',
        name: 'Base64 Encoder',
        description: 'Encode and decode Base64 strings',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/base64-encoder',
        icon: '⚡',
        popular: true,
    },
    {
        id: 'url-encoder',
        name: 'URL Encoder',
        description: 'Encode and decode URLs safely',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/url-encoder',
        icon: '🔗',
        popular: true,
    },
    {
        id: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode and inspect JSON Web Tokens',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/jwt-decoder',
        icon: '🔐',
        popular: true,
    },
    {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test regular expressions in real-time',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/regex-tester',
        icon: '.*',
        popular: true,
    },
    {
        id: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate random UUIDs/GUIDs instantly',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/uuid-generator',
        icon: '🆔',
        popular: true,
    },
    {
        id: 'sql-formatter',
        name: 'SQL Formatter',
        description: 'Format and beautify SQL queries',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/sql-formatter',
        icon: '🗄️',
        popular: true,
    },
    {
        id: 'timestamp-converter',
        name: 'Timestamp Tool',
        description: 'Convert Unix timestamps to human dates',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/timestamp-converter',
        icon: '⏰',
        popular: true,
    },
    {
        id: 'case-converter',
        name: 'Case Converter',
        description: 'Camel, snake, kebab & pascal case',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/case-converter',
        icon: 'Aa',
        popular: true,
    },
    {
        id: 'html-entities',
        name: 'HTML Entities',
        description: 'Encode and decode HTML entities',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/html-entities',
        icon: '🏷️',
    },
    {
        id: 'css-formatter',
        name: 'CSS Formatter',
        description: 'Format and minify CSS stylesheets',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/css-formatter',
        icon: '🎨',
    },
    {
        id: 'js-minifier',
        name: 'JavaScript Minifier',
        description: 'Minify JavaScript code',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/js-minifier',
        icon: '📦',
    },
    {
        id: 'slug-generator',
        name: 'Slug Generator',
        description: 'Generate URL-friendly slugs',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/slug-generator',
        icon: '🔤',
    },
    {
        id: 'backslash-escape',
        name: 'Backslash Escape',
        description: 'Escape/unescape special characters',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/backslash-escape',
        icon: '\\',
    },
    {
        id: 'xml-formatter',
        name: 'XML Formatter',
        description: 'Format and validate XML documents',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/xml-formatter',
        icon: '📰',
    },
    {
        id: 'yaml-validator',
        name: 'YAML Validator',
        description: 'Validate and format YAML files',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/yaml-validator',
        icon: '📑',
    },
    {
        id: 'html-formatter',
        name: 'HTML Formatter',
        description: 'Format and beautify HTML code',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/html-formatter',
        icon: '📄',
    },
    {
        id: 'cron-expression',
        name: 'Cron Expression',
        description: 'Generate and explain cron expressions',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/cron-expression',
        icon: '⏱️',
    },
    {
        id: 'api-tester',
        name: 'API Tester',
        description: 'Test REST API endpoints',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/api-tester',
        icon: '🌐',
    },
    {
        id: 'json-diff',
        name: 'JSON Diff',
        description: 'Compare two JSON objects',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/json-diff',
        icon: '🔍',
    },
    {
        id: 'json-path-tester',
        name: 'JSONPath Tester',
        description: 'Test JSONPath expressions',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/json-path-tester',
        icon: '🎯',
    },
    {
        id: 'graphql-formatter',
        name: 'GraphQL Formatter',
        description: 'Format GraphQL queries and schemas',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/graphql-formatter',
        icon: '◈',
    },
    {
        id: 'typescript-to-js',
        name: 'TypeScript to JS',
        description: 'Convert TypeScript to JavaScript',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/typescript-to-js',
        icon: '🔷',
    },
    {
        id: 'html-to-jsx',
        name: 'HTML to JSX',
        description: 'Convert HTML to React JSX',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/html-to-jsx',
        icon: '⚛️',
    },
    {
        id: 'curl-converter',
        name: 'cURL Converter',
        description: 'Convert cURL to code snippets',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/curl-converter',
        icon: '📡',
    },
    {
        id: 'http-header-parser',
        name: 'HTTP Header Parser',
        description: 'Parse and analyze HTTP headers',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/http-header-parser',
        icon: '📨',
    },
    {
        id: 'jwt-generator',
        name: 'JWT Generator',
        description: 'Create JSON Web Tokens',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/jwt-generator',
        icon: '🎫',
    },
    {
        id: 'base32-encoder',
        name: 'Base32 Encoder',
        description: 'Encode and decode Base32 strings',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/base32-encoder',
        icon: '🔠',
    },
    {
        id: 'ascii-art-generator',
        name: 'ASCII Art Generator',
        description: 'Convert text to ASCII art',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/ascii-art-generator',
        icon: '🎨',
    },
    {
        id: 'diff-checker',
        name: 'Code Diff Checker',
        description: 'Compare code and find differences',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/diff-checker',
        icon: '📊',
    },
    {
        id: 'json-minifier',
        name: 'JSON Minifier',
        description: 'Minify JSON by removing whitespace',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/json-minifier',
        icon: '🗜️',
    },
    {
        id: 'css-minifier',
        name: 'CSS Minifier',
        description: 'Minify CSS stylesheets',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/css-minifier',
        icon: '📉',
    },
    {
        id: 'html-minifier',
        name: 'HTML Minifier',
        description: 'Minify HTML documents',
        category: CATEGORIES.DEVELOPER,
        path: '/tools/html-minifier',
        icon: '📄',
    },

    // SECURITY TOOLS
    {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Create secure, random passwords',
        category: CATEGORIES.SECURITY,
        path: '/tools/password-generator',
        icon: '🔑',
        popular: true,
    },
    {
        id: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA-1, SHA-256 hashes',
        category: CATEGORIES.SECURITY,
        path: '/tools/hash-generator',
        icon: '#',
        popular: true,
    },
    {
        id: 'bcrypt-generator',
        name: 'Bcrypt Generator',
        description: 'Generate and verify bcrypt hashes',
        category: CATEGORIES.SECURITY,
        path: '/tools/bcrypt-generator',
        icon: '🔒',
    },
    {
        id: 'hmac-generator',
        name: 'HMAC Generator',
        description: 'Generate HMAC signatures',
        category: CATEGORIES.SECURITY,
        path: '/tools/hmac-generator',
        icon: '🔏',
    },
    {
        id: 'rsa-key-generator',
        name: 'RSA Key Generator',
        description: 'Generate RSA public/private key pairs',
        category: CATEGORIES.SECURITY,
        path: '/tools/rsa-key-generator',
        icon: '🗝️',
    },
    {
        id: 'aes-encrypt',
        name: 'AES Encrypt/Decrypt',
        description: 'Encrypt and decrypt with AES',
        category: CATEGORIES.SECURITY,
        path: '/tools/aes-encrypt',
        icon: '🔐',
    },
    {
        id: 'password-strength',
        name: 'Password Strength Checker',
        description: 'Check password strength and security',
        category: CATEGORIES.SECURITY,
        path: '/tools/password-strength',
        icon: '💪',
    },
    {
        id: 'ssl-checker',
        name: 'SSL Certificate Checker',
        description: 'Check SSL certificate details',
        category: CATEGORIES.SECURITY,
        path: '/tools/ssl-checker',
        icon: '🛡️',
    },
    {
        id: 'csp-generator',
        name: 'CSP Generator',
        description: 'Generate Content Security Policy',
        category: CATEGORIES.SECURITY,
        path: '/tools/csp-generator',
        icon: '🚧',
    },
    {
        id: 'totp-generator',
        name: 'TOTP Generator',
        description: 'Generate time-based OTP codes',
        category: CATEGORIES.SECURITY,
        path: '/tools/totp-generator',
        icon: '⏳',
    },

    // DESIGN TOOLS
    {
        id: 'color-converter',
        name: 'Color Converter',
        description: 'Convert Hex, RGB, HSL and CMYK',
        category: CATEGORIES.DESIGN,
        path: '/tools/color-converter',
        icon: '🎨',
        popular: true,
    },
    {
        id: 'gradient-generator',
        name: 'Gradient Generator',
        description: 'Create beautiful CSS gradients',
        category: CATEGORIES.DESIGN,
        path: '/tools/gradient-generator',
        icon: '🌈',
        popular: true,
    },
    {
        id: 'image-to-base64',
        name: 'Image to Base64',
        description: 'Convert images to Base64 strings',
        category: CATEGORIES.DESIGN,
        path: '/tools/image-to-base64',
        icon: '🖼️',
    },
    {
        id: 'color-palette',
        name: 'Color Palette Generator',
        description: 'Generate harmonious color palettes',
        category: CATEGORIES.DESIGN,
        path: '/tools/color-palette',
        icon: '🎭',
    },
    {
        id: 'color-picker',
        name: 'Color Picker',
        description: 'Pick colors from any source',
        category: CATEGORIES.DESIGN,
        path: '/tools/color-picker',
        icon: '🖌️',
    },
    {
        id: 'contrast-checker',
        name: 'Contrast Checker',
        description: 'Check color contrast for accessibility',
        category: CATEGORIES.DESIGN,
        path: '/tools/contrast-checker',
        icon: '👁️',
    },
    {
        id: 'box-shadow-generator',
        name: 'Box Shadow Generator',
        description: 'Create CSS box shadows visually',
        category: CATEGORIES.DESIGN,
        path: '/tools/box-shadow-generator',
        icon: '🌑',
    },
    {
        id: 'border-radius-generator',
        name: 'Border Radius Generator',
        description: 'Create CSS border radius visually',
        category: CATEGORIES.DESIGN,
        path: '/tools/border-radius-generator',
        icon: '⬜',
    },
    {
        id: 'glassmorphism-generator',
        name: 'Glassmorphism Generator',
        description: 'Create glass effect CSS',
        category: CATEGORIES.DESIGN,
        path: '/tools/glassmorphism-generator',
        icon: '🪟',
    },
    {
        id: 'neumorphism-generator',
        name: 'Neumorphism Generator',
        description: 'Create soft UI shadows',
        category: CATEGORIES.DESIGN,
        path: '/tools/neumorphism-generator',
        icon: '🔘',
    },
    {
        id: 'css-grid-generator',
        name: 'CSS Grid Generator',
        description: 'Create CSS Grid layouts visually',
        category: CATEGORIES.DESIGN,
        path: '/tools/css-grid-generator',
        icon: '📐',
    },
    {
        id: 'flexbox-generator',
        name: 'Flexbox Generator',
        description: 'Create Flexbox layouts visually',
        category: CATEGORIES.DESIGN,
        path: '/tools/flexbox-generator',
        icon: '📏',
    },
    {
        id: 'css-animation-generator',
        name: 'CSS Animation Generator',
        description: 'Create CSS animations visually',
        category: CATEGORIES.DESIGN,
        path: '/tools/css-animation-generator',
        icon: '🎬',
    },
    {
        id: 'favicon-generator',
        name: 'Favicon Generator',
        description: 'Generate favicons from images',
        category: CATEGORIES.DESIGN,
        path: '/tools/favicon-generator',
        icon: '⭐',
    },
    {
        id: 'placeholder-image',
        name: 'Placeholder Image',
        description: 'Generate placeholder images',
        category: CATEGORIES.DESIGN,
        path: '/tools/placeholder-image',
        icon: '🖼️',
    },
    {
        id: 'image-compressor',
        name: 'Image Compressor',
        description: 'Compress images without quality loss',
        category: CATEGORIES.DESIGN,
        path: '/tools/image-compressor',
        icon: '🗜️',
    },
    {
        id: 'image-resizer',
        name: 'Image Resizer',
        description: 'Resize images to any dimension',
        category: CATEGORIES.DESIGN,
        path: '/tools/image-resizer',
        icon: '📐',
    },
    {
        id: 'image-cropper',
        name: 'Image Cropper',
        description: 'Crop images to any size',
        category: CATEGORIES.DESIGN,
        path: '/tools/image-cropper',
        icon: '✂️',
    },
    {
        id: 'svg-optimizer',
        name: 'SVG Optimizer',
        description: 'Optimize and minify SVG files',
        category: CATEGORIES.DESIGN,
        path: '/tools/svg-optimizer',
        icon: '🖼️',
    },
    {
        id: 'font-preview',
        name: 'Font Preview',
        description: 'Preview Google Fonts instantly',
        category: CATEGORIES.DESIGN,
        path: '/tools/font-preview',
        icon: '🔤',
    },

    // CONTENT TOOLS
    {
        id: 'markdown-editor',
        name: 'Markdown Editor',
        description: 'Real-time Markdown editor and preview',
        category: CATEGORIES.CONTENT,
        path: '/tools/markdown-editor',
        icon: '📝',
        popular: true,
    },
    {
        id: 'lorem-ipsum',
        name: 'Lorem Ipsum',
        description: 'Generate placeholder text for designs',
        category: CATEGORIES.CONTENT,
        path: '/tools/lorem-ipsum',
        icon: '📄',
        popular: true,
    },
    {
        id: 'word-counter',
        name: 'Word Counter',
        description: 'Count words, characters & reading time',
        category: CATEGORIES.CONTENT,
        path: '/tools/word-counter',
        icon: '📊',
        popular: true,
    },
    {
        id: 'text-diff',
        name: 'Text Diff',
        description: 'Compare two texts and see differences',
        category: CATEGORIES.CONTENT,
        path: '/tools/text-diff',
        icon: '🔀',
    },
    {
        id: 'markdown-to-html',
        name: 'Markdown to HTML',
        description: 'Convert Markdown to HTML',
        category: CATEGORIES.CONTENT,
        path: '/tools/markdown-to-html',
        icon: '📝',
    },
    {
        id: 'html-to-markdown',
        name: 'HTML to Markdown',
        description: 'Convert HTML to Markdown',
        category: CATEGORIES.CONTENT,
        path: '/tools/html-to-markdown',
        icon: '📄',
    },
    {
        id: 'text-to-speech',
        name: 'Text to Speech',
        description: 'Convert text to audio',
        category: CATEGORIES.CONTENT,
        path: '/tools/text-to-speech',
        icon: '🔊',
    },
    {
        id: 'speech-to-text',
        name: 'Speech to Text',
        description: 'Convert audio to text',
        category: CATEGORIES.CONTENT,
        path: '/tools/speech-to-text',
        icon: '🎤',
    },
    {
        id: 'text-cleaner',
        name: 'Text Cleaner',
        description: 'Remove extra spaces and formatting',
        category: CATEGORIES.CONTENT,
        path: '/tools/text-cleaner',
        icon: '🧹',
    },
    {
        id: 'duplicate-remover',
        name: 'Duplicate Line Remover',
        description: 'Remove duplicate lines from text',
        category: CATEGORIES.CONTENT,
        path: '/tools/duplicate-remover',
        icon: '🗑️',
    },
    {
        id: 'line-sorter',
        name: 'Line Sorter',
        description: 'Sort lines alphabetically or numerically',
        category: CATEGORIES.CONTENT,
        path: '/tools/line-sorter',
        icon: '📋',
    },
    {
        id: 'text-reverser',
        name: 'Text Reverser',
        description: 'Reverse text or words',
        category: CATEGORIES.CONTENT,
        path: '/tools/text-reverser',
        icon: '🔄',
    },
    {
        id: 'find-replace',
        name: 'Find and Replace',
        description: 'Find and replace text patterns',
        category: CATEGORIES.CONTENT,
        path: '/tools/find-replace',
        icon: '🔍',
    },
    {
        id: 'emoji-picker',
        name: 'Emoji Picker',
        description: 'Search and copy emojis',
        category: CATEGORIES.CONTENT,
        path: '/tools/emoji-picker',
        icon: '😀',
    },
    {
        id: 'fancy-text',
        name: 'Fancy Text Generator',
        description: 'Generate stylish Unicode text',
        category: CATEGORIES.CONTENT,
        path: '/tools/fancy-text',
        icon: '✨',
    },

    // CONVERTER TOOLS
    {
        id: 'csv-to-json',
        name: 'CSV to JSON',
        description: 'Convert CSV data to JSON format',
        category: CATEGORIES.CONVERTER,
        path: '/tools/csv-to-json',
        icon: '📊',
    },
    {
        id: 'json-to-csv',
        name: 'JSON to CSV',
        description: 'Convert JSON array to CSV format',
        category: CATEGORIES.CONVERTER,
        path: '/tools/json-to-csv',
        icon: '📋',
    },
    {
        id: 'binary-converter',
        name: 'Binary Converter',
        description: 'Convert text to binary and vice versa',
        category: CATEGORIES.CONVERTER,
        path: '/tools/binary-converter',
        icon: '💾',
    },
    {
        id: 'hex-converter',
        name: 'Hex Converter',
        description: 'Convert text to hexadecimal',
        category: CATEGORIES.CONVERTER,
        path: '/tools/hex-converter',
        icon: '🔢',
    },
    {
        id: 'unicode-converter',
        name: 'Unicode Converter',
        description: 'Convert text to Unicode escape sequences',
        category: CATEGORIES.CONVERTER,
        path: '/tools/unicode-converter',
        icon: '🌐',
    },
    {
        id: 'octal-converter',
        name: 'Octal Converter',
        description: 'Convert between octal and decimal',
        category: CATEGORIES.CONVERTER,
        path: '/tools/octal-converter',
        icon: '8️⃣',
    },
    {
        id: 'roman-numeral',
        name: 'Roman Numeral Converter',
        description: 'Convert to/from Roman numerals',
        category: CATEGORIES.CONVERTER,
        path: '/tools/roman-numeral',
        icon: 'Ⅳ',
    },
    {
        id: 'number-base-converter',
        name: 'Number Base Converter',
        description: 'Convert between number bases',
        category: CATEGORIES.CONVERTER,
        path: '/tools/number-base-converter',
        icon: '🔢',
    },
    {
        id: 'json-to-xml',
        name: 'JSON to XML',
        description: 'Convert JSON to XML format',
        category: CATEGORIES.CONVERTER,
        path: '/tools/json-to-xml',
        icon: '📄',
    },
    {
        id: 'xml-to-json',
        name: 'XML to JSON',
        description: 'Convert XML to JSON format',
        category: CATEGORIES.CONVERTER,
        path: '/tools/xml-to-json',
        icon: '{}',
    },
    {
        id: 'csv-to-xml',
        name: 'CSV to XML',
        description: 'Convert CSV to XML format',
        category: CATEGORIES.CONVERTER,
        path: '/tools/csv-to-xml',
        icon: '📊',
    },
    {
        id: 'excel-to-json',
        name: 'Excel to JSON',
        description: 'Convert Excel files to JSON',
        category: CATEGORIES.CONVERTER,
        path: '/tools/excel-to-json',
        icon: '📗',
    },
    {
        id: 'pdf-to-text',
        name: 'PDF to Text',
        description: 'Extract text from PDF files',
        category: CATEGORIES.CONVERTER,
        path: '/tools/pdf-to-text',
        icon: '📕',
    },
    {
        id: 'image-format',
        name: 'Image Format Converter',
        description: 'Convert between image formats',
        category: CATEGORIES.CONVERTER,
        path: '/tools/image-format',
        icon: '🖼️',
    },
    {
        id: 'timezone-converter',
        name: 'Timezone Converter',
        description: 'Convert times between timezones',
        category: CATEGORIES.CONVERTER,
        path: '/tools/timezone-converter',
        icon: '🌍',
    },
    {
        id: 'currency-converter',
        name: 'Currency Converter',
        description: 'Convert between currencies',
        category: CATEGORIES.CONVERTER,
        path: '/tools/currency-converter',
        icon: '💱',
    },
    {
        id: 'temperature-converter',
        name: 'Temperature Converter',
        description: 'Convert Celsius, Fahrenheit, Kelvin',
        category: CATEGORIES.CONVERTER,
        path: '/tools/temperature-converter',
        icon: '🌡️',
    },

    // UTILITY TOOLS
    {
        id: 'unit-converter',
        name: 'Unit Converter',
        description: 'Convert Length, Weight & Temperature',
        category: CATEGORIES.UTILITY,
        path: '/tools/unit-converter',
        icon: '📏',
        popular: true,
    },
    {
        id: 'qr-generator',
        name: 'QR Code Generator',
        description: 'Generate QR codes for URLs and text',
        category: CATEGORIES.UTILITY,
        path: '/tools/qr-generator',
        icon: '📱',
        popular: true,
    },
    {
        id: 'random-generator',
        name: 'Random Generator',
        description: 'Generate random numbers or strings',
        category: CATEGORIES.UTILITY,
        path: '/tools/random-generator',
        icon: '🎲',
    },
    {
        id: 'text-manipulator',
        name: 'Text Manipulator',
        description: 'Various text transformation tools',
        category: CATEGORIES.UTILITY,
        path: '/tools/text-manipulator',
        icon: '✂️',
    },
    {
        id: 'qr-reader',
        name: 'QR Code Reader',
        description: 'Read and decode QR codes',
        category: CATEGORIES.UTILITY,
        path: '/tools/qr-reader',
        icon: '📷',
    },
    {
        id: 'barcode-generator',
        name: 'Barcode Generator',
        description: 'Generate various barcode formats',
        category: CATEGORIES.UTILITY,
        path: '/tools/barcode-generator',
        icon: '📊',
    },
    {
        id: 'stopwatch',
        name: 'Stopwatch',
        description: 'Simple stopwatch with lap times',
        category: CATEGORIES.UTILITY,
        path: '/tools/stopwatch',
        icon: '⏱️',
    },
    {
        id: 'countdown-timer',
        name: 'Countdown Timer',
        description: 'Set countdown timers',
        category: CATEGORIES.UTILITY,
        path: '/tools/countdown-timer',
        icon: '⏳',
    },
    {
        id: 'world-clock',
        name: 'World Clock',
        description: 'View time in different cities',
        category: CATEGORIES.UTILITY,
        path: '/tools/world-clock',
        icon: '🌍',
    },
    {
        id: 'date-calculator',
        name: 'Date Calculator',
        description: 'Calculate days between dates',
        category: CATEGORIES.UTILITY,
        path: '/tools/date-calculator',
        icon: '📅',
    },
    {
        id: 'age-calculator',
        name: 'Age Calculator',
        description: 'Calculate exact age from birthdate',
        category: CATEGORIES.UTILITY,
        path: '/tools/age-calculator',
        icon: '🎂',
    },
    {
        id: 'bmi-calculator',
        name: 'BMI Calculator',
        description: 'Calculate Body Mass Index',
        category: CATEGORIES.UTILITY,
        path: '/tools/bmi-calculator',
        icon: '⚖️',
    },
    {
        id: 'tip-calculator',
        name: 'Tip Calculator',
        description: 'Calculate tips and split bills',
        category: CATEGORIES.UTILITY,
        path: '/tools/tip-calculator',
        icon: '💵',
    },
    {
        id: 'loan-calculator',
        name: 'Loan Calculator',
        description: 'Calculate loan payments',
        category: CATEGORIES.UTILITY,
        path: '/tools/loan-calculator',
        icon: '🏦',
    },
    {
        id: 'percentage-calculator',
        name: 'Percentage Calculator',
        description: 'Calculate percentages easily',
        category: CATEGORIES.UTILITY,
        path: '/tools/percentage-calculator',
        icon: '%',
    },
    {
        id: 'discount-calculator',
        name: 'Discount Calculator',
        description: 'Calculate discounts and savings',
        category: CATEGORIES.UTILITY,
        path: '/tools/discount-calculator',
        icon: '🏷️',
    },
    {
        id: 'ip-lookup',
        name: 'IP Lookup',
        description: 'Get information about IP addresses',
        category: CATEGORIES.UTILITY,
        path: '/tools/ip-lookup',
        icon: '🌐',
    },
    {
        id: 'user-agent-parser',
        name: 'User Agent Parser',
        description: 'Parse and analyze user agent strings',
        category: CATEGORIES.UTILITY,
        path: '/tools/user-agent-parser',
        icon: '🖥️',
    },
    {
        id: 'mime-type-lookup',
        name: 'MIME Type Lookup',
        description: 'Find MIME types for file extensions',
        category: CATEGORIES.UTILITY,
        path: '/tools/mime-type-lookup',
        icon: '📁',
    },
    {
        id: 'email-validator',
        name: 'Email Validator',
        description: 'Validate email addresses',
        category: CATEGORIES.UTILITY,
        path: '/tools/email-validator',
        icon: '📧',
    },
    {
        id: 'credit-card-validator',
        name: 'Credit Card Validator',
        description: 'Validate credit card numbers',
        category: CATEGORIES.UTILITY,
        path: '/tools/credit-card-validator',
        icon: '💳',
    },

    // PRODUCTIVITY TOOLS
    {
        id: 'pomodoro-timer',
        name: 'Pomodoro Timer',
        description: 'Focus timer for productivity',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/pomodoro-timer',
        icon: '⏲️',
    },
    {
        id: 'todo-list',
        name: 'Todo List',
        description: 'Simple task management',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/todo-list',
        icon: '✅',
    },
    {
        id: 'notes',
        name: 'Quick Notes',
        description: 'Take quick notes locally',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/notes',
        icon: '📝',
    },
    {
        id: 'kanban-board',
        name: 'Kanban Board',
        description: 'Visual task management board',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/kanban-board',
        icon: '📋',
    },
    {
        id: 'habit-tracker',
        name: 'Habit Tracker',
        description: 'Track daily habits',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/habit-tracker',
        icon: '📈',
    },
    {
        id: 'meeting-cost',
        name: 'Meeting Cost Calculator',
        description: 'Calculate the cost of meetings',
        category: CATEGORIES.PRODUCTIVITY,
        path: '/tools/meeting-cost',
        icon: '💰',
    },

    // DATA TOOLS
    {
        id: 'data-generator',
        name: 'Fake Data Generator',
        description: 'Generate fake names, emails, addresses',
        category: CATEGORIES.DATA,
        path: '/tools/data-generator',
        icon: '🎭',
    },
    {
        id: 'sql-data-generator',
        name: 'SQL Data Generator',
        description: 'Generate SQL INSERT statements',
        category: CATEGORIES.DATA,
        path: '/tools/sql-data-generator',
        icon: '🗃️',
    },
    {
        id: 'json-data-generator',
        name: 'JSON Data Generator',
        description: 'Generate random JSON data',
        category: CATEGORIES.DATA,
        path: '/tools/json-data-generator',
        icon: '{}',
    },
    {
        id: 'csv-generator',
        name: 'CSV Generator',
        description: 'Generate CSV test data',
        category: CATEGORIES.DATA,
        path: '/tools/csv-generator',
        icon: '📊',
    },
    {
        id: 'credit-card-generator',
        name: 'Test Card Generator',
        description: 'Generate test credit card numbers',
        category: CATEGORIES.DATA,
        path: '/tools/credit-card-generator',
        icon: '💳',
    },
    {
        id: 'iban-generator',
        name: 'IBAN Generator',
        description: 'Generate test IBAN numbers',
        category: CATEGORIES.DATA,
        path: '/tools/iban-generator',
        icon: '🏦',
    },

    // NETWORK TOOLS
    {
        id: 'dns-lookup',
        name: 'DNS Lookup',
        description: 'Query DNS records',
        category: CATEGORIES.NETWORK,
        path: '/tools/dns-lookup',
        icon: '🔍',
    },
    {
        id: 'whois-lookup',
        name: 'WHOIS Lookup',
        description: 'Get domain registration info',
        category: CATEGORIES.NETWORK,
        path: '/tools/whois-lookup',
        icon: '📋',
    },
    {
        id: 'port-checker',
        name: 'Port Checker',
        description: 'Check if ports are open',
        category: CATEGORIES.NETWORK,
        path: '/tools/port-checker',
        icon: '🚪',
    },
    {
        id: 'http-status',
        name: 'HTTP Status Codes',
        description: 'Reference for HTTP status codes',
        category: CATEGORIES.NETWORK,
        path: '/tools/http-status',
        icon: '📡',
    },
    {
        id: 'url-parser',
        name: 'URL Parser',
        description: 'Parse and analyze URLs',
        category: CATEGORIES.NETWORK,
        path: '/tools/url-parser',
        icon: '🔗',
    },
    {
        id: 'mime-types',
        name: 'MIME Types',
        description: 'Reference for MIME types',
        category: CATEGORIES.NETWORK,
        path: '/tools/mime-types',
        icon: '📁',
    },

    // SEO TOOLS
    {
        id: 'meta-tag-generator',
        name: 'Meta Tag Generator',
        description: 'Generate SEO meta tags',
        category: CATEGORIES.SEO,
        path: '/tools/meta-tag-generator',
        icon: '🏷️',
    },
    {
        id: 'og-tag-generator',
        name: 'Open Graph Generator',
        description: 'Generate Open Graph tags',
        category: CATEGORIES.SEO,
        path: '/tools/og-tag-generator',
        icon: '📱',
    },
    {
        id: 'twitter-card-generator',
        name: 'Twitter Card Generator',
        description: 'Generate Twitter Card tags',
        category: CATEGORIES.SEO,
        path: '/tools/twitter-card-generator',
        icon: '🐦',
    },
    {
        id: 'robots-txt-generator',
        name: 'Robots.txt Generator',
        description: 'Generate robots.txt files',
        category: CATEGORIES.SEO,
        path: '/tools/robots-txt-generator',
        icon: '🤖',
    },
    {
        id: 'sitemap-generator',
        name: 'Sitemap Generator',
        description: 'Generate XML sitemaps',
        category: CATEGORIES.SEO,
        path: '/tools/sitemap-generator',
        icon: '🗺️',
    },
    {
        id: 'keyword-density',
        name: 'Keyword Density Checker',
        description: 'Analyze keyword density in text',
        category: CATEGORIES.SEO,
        path: '/tools/keyword-density',
        icon: '📊',
    },
    {
        id: 'slug-checker',
        name: 'URL Slug Checker',
        description: 'Check and optimize URL slugs',
        category: CATEGORIES.SEO,
        path: '/tools/slug-checker',
        icon: '🔗',
    },
    {
        id: 'schema-generator',
        name: 'Schema Markup Generator',
        description: 'Generate structured data markup',
        category: CATEGORIES.SEO,
        path: '/tools/schema-generator',
        icon: '📝',
    },

    // MATH TOOLS
    {
        id: 'scientific-calculator',
        name: 'Scientific Calculator',
        description: 'Advanced scientific calculations',
        category: CATEGORIES.MATH,
        path: '/tools/scientific-calculator',
        icon: '🔢',
    },
    {
        id: 'matrix-calculator',
        name: 'Matrix Calculator',
        description: 'Matrix operations and calculations',
        category: CATEGORIES.MATH,
        path: '/tools/matrix-calculator',
        icon: '📐',
    },
    {
        id: 'equation-solver',
        name: 'Equation Solver',
        description: 'Solve mathematical equations',
        category: CATEGORIES.MATH,
        path: '/tools/equation-solver',
        icon: '➗',
    },
    {
        id: 'prime-checker',
        name: 'Prime Number Checker',
        description: 'Check if a number is prime',
        category: CATEGORIES.MATH,
        path: '/tools/prime-checker',
        icon: '🔢',
    },
    {
        id: 'factorial-calculator',
        name: 'Factorial Calculator',
        description: 'Calculate factorials',
        category: CATEGORIES.MATH,
        path: '/tools/factorial-calculator',
        icon: '!',
    },
    {
        id: 'fibonacci-generator',
        name: 'Fibonacci Generator',
        description: 'Generate Fibonacci sequences',
        category: CATEGORIES.MATH,
        path: '/tools/fibonacci-generator',
        icon: '🌀',
    },
    {
        id: 'gcd-lcm-calculator',
        name: 'GCD/LCM Calculator',
        description: 'Calculate GCD and LCM',
        category: CATEGORIES.MATH,
        path: '/tools/gcd-lcm-calculator',
        icon: '🔢',
    },
    {
        id: 'statistics-calculator',
        name: 'Statistics Calculator',
        description: 'Calculate mean, median, mode',
        category: CATEGORIES.MATH,
        path: '/tools/statistics-calculator',
        icon: '📈',
    },
];

// Helper functions
export const getToolById = (id) => {
    return toolsList.find((tool) => tool.id === id);
};

export const getToolsByCategory = (category) => {
    if (category === CATEGORIES.ALL) return toolsList;
    return toolsList.filter((tool) => tool.category === category);
};

export const getPopularTools = () => {
    return toolsList.filter((tool) => tool.popular);
};

export const searchTools = (query) => {
    const lowerQuery = query.toLowerCase();
    return toolsList.filter(
        (tool) =>
            tool.name.toLowerCase().includes(lowerQuery) ||
            tool.description.toLowerCase().includes(lowerQuery)
    );
};

/**
 * Get all AI tools
 * @returns {Array} AI tools
 */
export const getAITools = () => {
    return toolsList.filter((tool) => tool.category === CATEGORIES.AI);
};

/**
 * Get tools that require API keys
 * @returns {Array} Tools requiring API keys
 */
export const getToolsRequiringApiKey = () => {
    return toolsList.filter((tool) => tool.requiresApiKey === true);
};
